---
- name: Ensure dnsmasq is installed
  package:
    name: dnsmasq
    state: present

- name: Ensure systemd-resolved isn't set up to handle DNS resolution
  service:
    name: systemd-resolved
    state: stopped
    enabled: false
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] is version('18.04', '>=')

- name: Ensure dnsmasq config file is installed
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    validate: /usr/sbin/dnsmasq -C %s --test
    mode: 0644
  notify: restart dnsmasq
